---
- name: Install jpstack on Linux Distribution
  hosts: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Set distro variable
      set_fact:
        distro: "{{ ansible_distribution | lower | regex_replace(' ', '_') }}"

    - name: Print distribution name
      debug:
        var: distro

    - name: Check if distro role exists
      stat:
        path: "roles/{{ distro }}"
      register: distro_role
    
    - name: Fail if distro role does not exist
      fail:
        msg: "No role found for distribution: {{ distro }}"
      when: not distro_role.stat.exists

    - name: Include distro role dynamically
      include_role:
        name: "{{ distro }}"

  roles:
    - common
