---
- name: Detect system distribution and apply corresponding setup
  hosts: local
  become: yes
  gather_facts: yes

  tasks:
    - name: Determine system distribution
      set_fact:
        distro: "{{ ansible_distribution | lower | regex_replace(' ', '_') }}"

    - name: Display system distribution
      debug:
        var: distro

    - name: Verify if a setup role exists for the system distribution
      stat:
        path: "roles/{{ distro }}"
      register: distro_role
    
    - name: Abort if no role exists for the system distribtion
      fail:
        msg: "No role found for distribution: {{ distro }}"
      when: not distro_role.stat.exists

    - name: Include system-specific role dynamically
      include_role:
        name: "{{ distro }}"

  roles:
    - common
