---
- name: Stage 0 -- Prerequisites
  include_tasks: stage_0_prerequisites.yml
  when: "'stage_0' in stages_to_run.split(',')"

- name: Stage 1 -- Core System Setup
  include_tasks: stage_1_core_system.yml
  when: "'stage_1' in stages_to_run.split(',')"

- name: Stage 2 -- Optimize Mirrors and Install Drivers
  include_tasks: stage_2_optimize_and_drivers.yml
  when: "'stage_2' in stages_to_run.split(',')"

- name: Stage 3 -- Disk Partitioning and Filesystems
  include_tasks: stage_3_disk_partitioning.yml
  when: "'stage_3' in stages_to_run.split(',')"

- name: Stage 4 -- Bootstrap and Final Configuration
  include_tasks: stage_4_bootstrap_and_config.yml
  when: "'stage_4' in stages_to_run.split(',')"
